config/routes.rb
CloudAnalytics::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :server_instances

  resources :users

  resources :master_servers

end

app/models/master_server.rb
class MasterServer < ActiveRecord::Base
  attr_accessible :group_hour, :group_res, :ind_hour, :ind_resource, :org_hour, :org_res, :server_region, :servername, :serversize
  has_many :server_instances
end

app/models/server_instance.rb
class ServerInstance < ActiveRecord::Base
  attr_accessible :end_time, :masterid, :ownerid, :recent_exe_date, :recentbill, :start_time, :status, :totalbill
  belongs_to :master_server,:user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :usertype
  has_many :server_instances
  validates :username, :usertype => { :maximum => 140 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/master_servers_controller.rb
class MasterServersController < ApplicationController
  # GET /master_servers
  # GET /master_servers.json
  def index
    @master_servers = MasterServer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @master_servers }
    end
  end

  # GET /master_servers/1
  # GET /master_servers/1.json
  def show
    @master_server = MasterServer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @master_server }
    end
  end

  # GET /master_servers/new
  # GET /master_servers/new.json
  def new
    @master_server = MasterServer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @master_server }
    end
  end

  # GET /master_servers/1/edit
  def edit
    @master_server = MasterServer.find(params[:id])
  end

  # POST /master_servers
  # POST /master_servers.json
  def create
    @master_server = MasterServer.new(params[:master_server])

    respond_to do |format|
      if @master_server.save
        format.html { redirect_to @master_server, notice: 'Master server was successfully created.' }
        format.json { render json: @master_server, status: :created, location: @master_server }
      else
        format.html { render action: "new" }
        format.json { render json: @master_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /master_servers/1
  # PUT /master_servers/1.json
  def update
    @master_server = MasterServer.find(params[:id])

    respond_to do |format|
      if @master_server.update_attributes(params[:master_server])
        format.html { redirect_to @master_server, notice: 'Master server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @master_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_servers/1
  # DELETE /master_servers/1.json
  def destroy
    @master_server = MasterServer.find(params[:id])
    @master_server.destroy

    respond_to do |format|
      format.html { redirect_to master_servers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/server_instances_controller.rb
class ServerInstancesController < ApplicationController
  # GET /server_instances
  # GET /server_instances.json
  def index
    @server_instances = ServerInstance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @server_instances }
    end
  end

  # GET /server_instances/1
  # GET /server_instances/1.json
  def show
    @server_instance = ServerInstance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server_instance }
    end
  end

  # GET /server_instances/new
  # GET /server_instances/new.json
  def new
    @server_instance = ServerInstance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server_instance }
    end
  end

  # GET /server_instances/1/edit
  def edit
    @server_instance = ServerInstance.find(params[:id])
  end

  # POST /server_instances
  # POST /server_instances.json
  def create
    @server_instance = ServerInstance.new(params[:server_instance])

    respond_to do |format|
      if @server_instance.save
        format.html { redirect_to @server_instance, notice: 'Server instance was successfully created.' }
        format.json { render json: @server_instance, status: :created, location: @server_instance }
      else
        format.html { render action: "new" }
        format.json { render json: @server_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /server_instances/1
  # PUT /server_instances/1.json
  def update
    @server_instance = ServerInstance.find(params[:id])

    respond_to do |format|
      if @server_instance.update_attributes(params[:server_instance])
        format.html { redirect_to @server_instance, notice: 'Server instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_instances/1
  # DELETE /server_instances/1.json
  def destroy
    @server_instance = ServerInstance.find(params[:id])
    @server_instance.destroy

    respond_to do |format|
      format.html { redirect_to server_instances_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def contact
  end
  
  def signup
  end
  
  def signin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/master_servers_helper.rb
module MasterServersHelper
end

app/helpers/server_instances_helper.rb
module ServerInstancesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    cloud Analytics - by diligent_ss
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Cloud Analytics", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/master_servers/_form.html.erb
<%= form_for(@master_server) do |f| %>
  <% if @master_server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master_server.errors.count, "error") %> prohibited this master_server from being saved:</h2>

      <ul>
      <% @master_server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :servername %><br />
    <%= f.text_field :servername %>
  </div>
  <div class="field">
    <%= f.label :serversize %><br />
    <%= f.text_field :serversize %>
  </div>
  <div class="field">
    <%= f.label :server_region %><br />
    <%= f.text_field :server_region %>
  </div>
  <div class="field">
    <%= f.label :ind_resource %><br />
    <%= f.text_field :ind_resource %>
  </div>
  <div class="field">
    <%= f.label :ind_hour %><br />
    <%= f.text_field :ind_hour %>
  </div>
  <div class="field">
    <%= f.label :org_res %><br />
    <%= f.text_field :org_res %>
  </div>
  <div class="field">
    <%= f.label :org_hour %><br />
    <%= f.text_field :org_hour %>
  </div>
  <div class="field">
    <%= f.label :group_res %><br />
    <%= f.text_field :group_res %>
  </div>
  <div class="field">
    <%= f.label :group_hour %><br />
    <%= f.number_field :group_hour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/master_servers/edit.html.erb
<h1>Editing master_server</h1>

<%= render 'form' %>

<%= link_to 'Show', @master_server %> |
<%= link_to 'Back', master_servers_path %>

app/views/master_servers/index.html.erb
<h1>Listing master_servers</h1>

<table>
  <tr>
    <th>Servername</th>
    <th>Serversize</th>
    <th>Server region</th>
    <th>Ind resource</th>
    <th>Ind hour</th>
    <th>Org res</th>
    <th>Org hour</th>
    <th>Group res</th>
    <th>Group hour</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @master_servers.each do |master_server| %>
  <tr>
    <td><%= master_server.servername %></td>
    <td><%= master_server.serversize %></td>
    <td><%= master_server.server_region %></td>
    <td><%= master_server.ind_resource %></td>
    <td><%= master_server.ind_hour %></td>
    <td><%= master_server.org_res %></td>
    <td><%= master_server.org_hour %></td>
    <td><%= master_server.group_res %></td>
    <td><%= master_server.group_hour %></td>
    <td><%= link_to 'Show', master_server %></td>
    <td><%= link_to 'Edit', edit_master_server_path(master_server) %></td>
    <td><%= link_to 'Destroy', master_server, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Master server', new_master_server_path %>

app/views/master_servers/new.html.erb
<h1>New master_server</h1>

<%= render 'form' %>

<%= link_to 'Back', master_servers_path %>

app/views/master_servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Servername:</b>
  <%= @master_server.servername %>
</p>

<p>
  <b>Serversize:</b>
  <%= @master_server.serversize %>
</p>

<p>
  <b>Server region:</b>
  <%= @master_server.server_region %>
</p>

<p>
  <b>Ind resource:</b>
  <%= @master_server.ind_resource %>
</p>

<p>
  <b>Ind hour:</b>
  <%= @master_server.ind_hour %>
</p>

<p>
  <b>Org res:</b>
  <%= @master_server.org_res %>
</p>

<p>
  <b>Org hour:</b>
  <%= @master_server.org_hour %>
</p>

<p>
  <b>Group res:</b>
  <%= @master_server.group_res %>
</p>

<p>
  <b>Group hour:</b>
  <%= @master_server.group_hour %>
</p>


<%= link_to 'Edit', edit_master_server_path(@master_server) %> |
<%= link_to 'Back', master_servers_path %>

app/views/server_instances/_form.html.erb
<%= form_for(@server_instance) do |f| %>
  <% if @server_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_instance.errors.count, "error") %> prohibited this server_instance from being saved:</h2>

      <ul>
      <% @server_instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ownerid %><br />
    <%= f.number_field :ownerid %>
  </div>
  <div class="field">
    <%= f.label :masterid %><br />
    <%= f.number_field :masterid %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :recentbill %><br />
    <%= f.text_field :recentbill %>
  </div>
  <div class="field">
    <%= f.label :recent_exe_date %><br />
    <%= f.date_select :recent_exe_date %>
  </div>
  <div class="field">
    <%= f.label :totalbill %><br />
    <%= f.text_field :totalbill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_instances/edit.html.erb
<h1>Editing server_instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @server_instance %> |
<%= link_to 'Back', server_instances_path %>

app/views/server_instances/index.html.erb
<h1>Listing server_instances</h1>

<table>
  <tr>
    <th>Ownerid</th>
    <th>Masterid</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Status</th>
    <th>Recentbill</th>
    <th>Recent exe date</th>
    <th>Totalbill</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @server_instances.each do |server_instance| %>
  <tr>
    <td><%= server_instance.ownerid %></td>
    <td><%= server_instance.masterid %></td>
    <td><%= server_instance.start_time %></td>
    <td><%= server_instance.end_time %></td>
    <td><%= server_instance.status %></td>
    <td><%= server_instance.recentbill %></td>
    <td><%= server_instance.recent_exe_date %></td>
    <td><%= server_instance.totalbill %></td>
    <td><%= link_to 'Show', server_instance %></td>
    <td><%= link_to 'Edit', edit_server_instance_path(server_instance) %></td>
    <td><%= link_to 'Destroy', server_instance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server instance', new_server_instance_path %>

app/views/server_instances/new.html.erb
<h1>New server_instance</h1>

<%= render 'form' %>

<%= link_to 'Back', server_instances_path %>

app/views/server_instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ownerid:</b>
  <%= @server_instance.ownerid %>
</p>

<p>
  <b>Masterid:</b>
  <%= @server_instance.masterid %>
</p>

<p>
  <b>Start time:</b>
  <%= @server_instance.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @server_instance.end_time %>
</p>

<p>
  <b>Status:</b>
  <%= @server_instance.status %>
</p>

<p>
  <b>Recentbill:</b>
  <%= @server_instance.recentbill %>
</p>

<p>
  <b>Recent exe date:</b>
  <%= @server_instance.recent_exe_date %>
</p>

<p>
  <b>Totalbill:</b>
  <%= @server_instance.totalbill %>
</p>


<%= link_to 'Edit', edit_server_instance_path(@server_instance) %> |
<%= link_to 'Back', server_instances_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<table>
  <tr>
    <td><h1>Cloud Analystics</h1></td>
  </tr>
  <tr>
    <td align="center">
      <p>
        welcome to Cloud Analytics
      </p>
    </td>
  </tr>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :usertype %><br />
    <%= f.text_field :usertype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Usertype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.usertype %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Usertype:</b>
  <%= @user.usertype %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>